name: PowerEssentials
main: angga7togk\poweressentials\PowerEssentials
api: 5.0.0
version: 1.0.0
author: Angga7Togk

permissions:
  poweressentials.setlobby:
    default: op
  poweressentials.lobby:
    default: true
  poweressentials.fly:
    default: op
  poweressentials.fly.other:
    default: op
  poweressentials.antinamespace.bypass:
    default: op
  poweressentials.gamemode:
    default: op
  poweressentials.gamemode.other:
    default: op
  poweressentials.gmc:
    default: op
  poweressentials.gms:
    default: op
  poweressentials.gma:
    default: op
  poweressentials.gmspc:
    default: op
  poweressentials.nickname:
    default: op
  poweressentials.nickname.other:
    default: op
  poweressentials.home:
    default: true
  poweressentials.sethome:
    default: true
  poweressentials.delhome:
    default: true
  poweressentials.coordinates:
    default: true
  poweressentials.warp:
    default: true
  poweressentials.addwarp:
    default: op
  poweressentials.delwarp:
    default: op
  poweressentials.heal:
    default: op
  poweressentials.heal.other:
    default: op
  poweressentials.feed:
    default: op
  poweressentials.feed.other:
    default: op
