##################################
#         PowerEssentials        #
##################################

# config version
# !!!dont change this!!!!
config-version: 1.0

# You can customize your own language via the language folder, just create it
# example = id.yml
# then change here to 'id'
language: en

# on join force set gamemode
gamemode-join-enable: true
gamemode-join: SURVIVAL

# on join force spawn to lobby position
spawn-lobby-join: true

# Players with space names are prohibited from entering
anti-namespace: false

# show vanilla coordinates
show-coordinates: true

##################################
#            Nicknames           #
##################################
# maximum number of characters
nickname-max-char: 15

# blacklist nickname
# This feature only works for /nickname
blacklist-nicknames:
  - admin
  - owner
  - staff

##################################
#            Commands            #
##################################
# commands option disable and enabled
# set false to disable
# set true to enable
commands:
  lobby: true
  fly: true
  gamemode: true
  nickname: true
  home: true


##################################
#               HOME             #
##################################
# blacklist set home in world
home-world-blacklists:
  - world_nether
  - world_the_end

# Permission Limit
# if you enable this feature, you can limit the number of homes per player
home-permission-limit: false
home-permission-default-limit: 3

home-permission-limits:
  homelimit.5: 5
  homelimit.10: 10


